--------------------------------------------------
--      ____  ____ _____                        --
--     |    \|  _ )_   _|___ ____   __  __      --
--     | |_  )  _ \ | |/ ·__|  _ \_|  \/  |     --
--     |____/|____/ |_|\____/\_____|_/\/\_|     --
--                                              --
--------------------------------------------------

local LANG = 'it:'

local function run(msg, matches)
    if is_sudo(msg) then
        -------------
        -- Plugins --
        -------------

        redis:set('lang', LANG)

        -- global --
        set_text('require_sudo', '🚫 Questo comando richiede i privilegi di sudo.')
        set_text('require_admin', '🚫 Questo comando richiede privilegi da admin o superiori.')
        set_text('require_support', '🚫 Questo comando richiede privilegi da support o superiori.')
        set_text('require_owner', '🚫 Questo comando richiede privilegi da owner o superiori.')
        set_text('require_mod', '🚫 Questo comando richiede privilegi da moderatore o superiori.')
        set_text('require_rank', '🚫 Non puoi eseguire questo comando su qualcuno che ha privilegi superiori o uguali ai tuoi!')
        set_text('errorTryAgain', 'Errore, prova di nuovo.')
        set_text('opsError', 'Ops, errore.')
        set_text('useYourGroups', 'Usalo nei tuoi gruppi!')
        set_text('user', 'Utente ')
        set_text('kicked', ' rimosso.')
        set_text('banned', ' bannato.')
        set_text('unbanned', ' unbannato.')
        set_text('gbanned', ' bannato globalmente.')
        set_text('ungbanned', ' unbannato globalmente.')

        -- seedbot.lua --
        set_text('sender', 'Mittente: ')
        set_text('receiver', 'Ricevente: ')
        set_text('msgText', 'Testo del messaggio: ')

        -- utils.lua --
        set_text('errorImageDownload', 'Errore nel download dell\'immagine.')
        set_text('banListStart', 'Lista ban:\n\n')
        set_text('gbanListStart', 'Lista ban globali:\n\n')
        set_text('mutedUsersStart', 'Utenti muti di:')
        set_text('mutedTypesStart', 'Muti di:')
        set_text('mute', 'Muto ')
        set_text('alreadyEnabled', ' già attivato.')
        set_text('enabled', ' attivato.')
        set_text('alreadyDisabled', ' già disattivato.')
        set_text('disabled', ' disattivato')
        set_text('noAutoKick', 'Non puoi rimuoverti da solo.')
        set_text('noAutoBan', 'Non puoi bannarti da solo.')

        -- admin.lua --
        set_text('sendNewPic', 'Mandami la nuova foto.')
        set_text('botPicChanged', 'Foto cambiata!')
        set_text('logSet', 'Il log è stato aggiunto.')
        set_text('logUnset', 'Il log è stato rimosso.')
        set_text('markRead', 'Segna come già letto')
        set_text('pmSent', 'Messaggio mandato')
        set_text('cantBlockAdmin', 'Non puoi bloccare un admin.')
        set_text('userBlocked', 'Utente bloccato.')
        set_text('userUnblocked', 'Utente sbloccato.')
        set_text('contactListSent', 'Ti ho mandato in privato la lista dei contatti nel formato da te richiesto.')
        set_text('removedFromContacts', ' rimosso dai contatti.')
        set_text('addedToContacts', ' aggiunto ai contatti.')
        set_text('contactMissing', 'Non ho il tuo numero di telefono!')
        set_text('chatListSent', 'Ti ho mandato in privato la lista delle chat nel formato da te richiesto.')
        set_text('gbansSync', 'Lista ban globali sincronizzata.')
        set_text('longidUpdate', 'Aggiorna long_ID.')
        set_text('alreadyLog', 'Già un gruppo di log.')
        set_text('notLog', 'Non un gruppo di log.')
        set_text('backupDone', 'Backup eseguito, ti invio il log in privato.')

        -- anti_spam.lua --
        set_text('blockedForSpam', ' bloccato (SPAM).')
        set_text('floodNotAdmitted', 'Il flood non è ammesso.\n')
        set_text('statusRemoved', 'Utente rimosso.')
        set_text('gbannedFrom', ' bannato globalmente da ')

        -- arabic_lock.lua --
        set_text('arabicNotAllowed', 'L\'arabo/Il persiano non è ammesso.\n')
        set_text('statusRemovedMsgDeleted', 'Utente rimosso/messaggio eliminato.')

        -- banhammer.lua --
        set_text('noUsernameFound', 'Non trovo nessun utente con quell\'username.')
        set_text('massacre', 'Massacro => X')

        -- bot.lua --
        set_text('botOn', 'Sono tornata. 😏')
        set_text('botOff', 'Nulla da fare qui. 🚀')

        -- botinteract.lua --
        set_text('botSet', ' è stato salvato per l\'interazione con la chat.')
        set_text('botUnset', ' è stato rimosso dai bot con cui interagire.')
        set_text('sendMeMedia', 'Mandami ora il media che vuoi che io inoltri.')
        set_text('mediaForwarded', 'Media inoltrato.')

        -- feedback.lua --
        set_text('feedStart', '@EricSolinas hai ricevuto un feedback: #newfeedback\n\nMittente')
        set_text('feedName', '\nNome: ')
        set_text('feedSurname', '\nCognome: ')
        set_text('feedUsername', '\nUsername: @')
        set_text('feedSent', 'Feedback inviato!')

        -- filemanager.lua --
        set_text('backHomeFolder', 'Sei tornato alla cartella base: ')
        set_text('youAreHere', 'Sei qui: ')
        set_text('folderCreated', 'Cartella \'X\' creata.')
        set_text('folderDeleted', 'Cartella \'X\' eliminata.')
        set_text('fileCreatedWithContent', ' creato con \'X\' come contenuto.')
        set_text('copiedTo', ' copiato in ')
        set_text('movedTo', ' spostato in ')
        set_text('sendingYou', 'Ti sto inviando ')
        set_text('useQuoteOnFile', 'Usa \'rispondi\' sul file che vuoi che scarichi.')
        set_text('needMedia', 'Mi serve un file.')
        set_text('fileDownloadedTo', 'File scaricato in: ')
        set_text('errorDownloading', 'Errore durante il download: ')

        -- flame.lua --
        set_text('cantFlameHigher', 'Non puoi flammare un mod/owner/admin/sudo/!')
        set_text('noAutoFlame', 'Non posso flammarmi da sola trisomico del cazzo!')
        set_text('hereIAm', 'Eccomi qua!')
        set_text('stopFlame', 'Si si mi fermo però porca madonna.')
        set_text('flaming', 'Sto flammando: ')
        set_text('errorParameter', 'Errore variabile redis mancante.')

        -- help.lua --
        set_text('require_higher', '🚫 Questo plugin richiede privilegi superiori a quelli che possiedi.\n')
        set_text('pluginListStart', 'ℹ️Lista plugin: \n\n')
        set_text('helpInfo', 'ℹ️Scrivi "!help <plugin_name>|<plugin_number>" per maggiori informazioni su quel plugin.\nℹ️O "!helpall" per mostrare tutte le informazioni.')
        set_text('errorNoPlugin', 'Questo plugin non esiste o non ha una descrizione.')
        set_text('doYourBusiness', 'Ma una sportina di cazzi tuoi no?')
        set_text('helpIntro', 'Ogni \'#\' può essere sostituito con i simboli \'/\' o \'!\'.\nTutti i comandi sono Case Insensitive.\nLe parentesi quadre significano opzionale.\nLe parentesi tonde indicano una scelta evidenziata da \'|\' che significa "oppure".\n\n')
        set_text('youTried', 'Ci hai provato, non avrai un help più dettagliato di quello che ti spetta, pezzente.')

        -- games --
        set_text('groupAlreadySignedUp', 'Gruppo già registrato.')
        set_text('groupSignedUp', 'Gruppo registrato con i valori di default.')
        set_text('requireGroupSignUp', 'Prima di giocare è necessario far registrare il gruppo.')
        set_text('challenge', 'SFIDA')
        set_text('challenger', 'Sfidante: ')
        set_text('challenged', 'Sfidato: ')
        set_text('challengeModTerminated', 'Sfida terminata da un moderatore.')
        set_text('challengeRejected', 'X ha rifiutato la sfida, codardo!')
        set_text('cantChallengeYourself', 'Non puoi sfidarti da solo.')
        set_text('cantChallengeMe', 'Non puoi sfidare me, perderesti di sicuro.')
        set_text('notAccepted', 'Non ancora accettata.')
        set_text('accepted', 'In corso.')
        set_text('notYourTurn', 'Non è il tuo turno.')
        set_text('yourTurn', ' sta a te.')
        set_text('challengeEnd', 'Morto, Sfida terminata.')
        set_text('noChallenge', 'Nessuna sfida in corso.')
        set_text('errorOngoingChallenge', 'Impossibile avviare più sfide contemporaneamente.')
        set_text('challengeSet', 'Sfida avviata, X può accettare con /accept o rifiutare con /reject.')
        set_text('wrongPlayer', 'Non sei tu X.')
        set_text('deaths', 'Numero morti: ')
        set_text('duels', 'Sfide totali: ')
        set_text('wonduels', 'Sfide vinte: ')
        set_text('lostduels', 'Sfide perse: ')
        set_text('actualstreak', 'Serie attuale: ')
        set_text('longeststreak', 'Serie più lunga: ')
        set_text('attempts', 'Tentativi totali: ')
        set_text('score', 'Punteggio: ')
        set_text('cheating', 'Trucco inserito.')
        set_text('scoreLeaderboard', 'Classifica punti\n')
        set_text('attemptsLeaderboard', 'Classifica tentativi\n')
        set_text('deathsLeaderboard', 'Classifica morti\n')
        set_text('streakLeaderboard', 'Classifica serie\n')
        set_text('duelsLeaderboard', 'Classifica sfide\n')
        set_text('victoriesLeaderboard', 'Classifica vittorie\n')
        set_text('defeatsLeaderboard', 'Classifica sconfitte\n')

        -- goodbyewelcome.lua --
        set_text('newWelcome', 'Nuovo messaggio di benvenuto:\n')
        set_text('newGoodbye', 'Nuovo messaggio di addio:\n')
        set_text('welcomeRemoved', 'Benvenuto rimosso.')
        set_text('goodbyeRemoved', 'Addio rimosso.')
        set_text('newWelcomeNumber', 'Il benvenuto sarà mandato ogni X membri.')
        set_text('neverWelcome', 'Il messaggio di benvenuto non sarà più mandato.')
        set_text('noSetValue', 'Nessun valore impostato.')

        -- groups --
        set_text('newDescription', 'Nuova descrizione:\n')
        set_text('noDescription', 'Nessuna descrizione disponibile.')
        set_text('description', 'Descrizione chat: ')
        set_text('newRules', 'Nuove regole:\n')
        set_text('noRules', 'Nessuna regola disponibile.')
        set_text('rules', 'Regole chat: ')
        set_text('sendNewGroupPic', 'Mandami la nuova foto del gruppo.')
        set_text('photoSaved', 'Foto salvata.')
        set_text('groupSettings', 'Impostazioni gruppo: ')
        set_text('supergroupSettings', 'Impostazioni supergruppo: ')
        set_text('noGroups', 'Nessun gruppo al momento.')
        set_text('errorFloodRange', 'Errore, il range è [3-200]')
        set_text('floodSet', 'Il flood è stato impostato a ')
        set_text('noOwnerCallAdmin', 'Nessun proprietario, chiedi ad un admin di settarne uno.')
        set_text('ownerIs', 'Il proprietario del gruppo è ')
        set_text('errorCreateLink', 'Errore creazione link d\'invito.\nNon sono la creatrice.')
        set_text('errorCreateSuperLink', 'Errore creazione link d\'invito.\nNon sono la creatrice.\n\nSe hai il link usa /setlink per impostarlo')
        set_text('createLinkInfo', 'Crea un link usando /newlink.')
        set_text('linkCreated', 'Nuovo link creato.')
        set_text('groupLink', 'Link\n')
        set_text('adminListStart', 'Admins:\n')
        set_text('alreadyMod', ' è già un mod.')
        set_text('promoteMod', ' è stato promosso a mod.')
        set_text('notMod', ' non è un mod.')
        set_text('demoteMod', ' è stato degradato da mod.')
        set_text('noGroupMods', 'Nessun moderatore in questo gruppo.')
        set_text('modListStart', 'Moderatori di ')
        set_text('muteUserAdd', ' aggiunto alla lista degli utenti silenziati.')
        set_text('muteUserRemove', ' rimosso dalla lista degli utenti silenziati.')
        set_text('modlistCleaned', 'Lista mod svuotata.')
        set_text('rulesCleaned', 'Regole svuotate.')
        set_text('descriptionCleaned', 'Descrizione svuotata.')
        set_text('mutelistCleaned', 'Lista muti svuotata.')

        -- info.lua --
        set_text('info', 'INFO')
        set_text('youAre', '\nTu sei')
        set_text('name', '\nNome: ')
        set_text('surname', '\nCognome: ')
        set_text('username', '\nUsername: ')
        set_text('phone', '\nTelefono: ')
        set_text('rank', '\nRango: ')
        set_text('date', '\nData: ')
        set_text('totalMessages', '\nMessaggi totali: ')
        set_text('otherInfo', '\nAltre informazioni: ')
        set_text('youAreWriting', '\n\nStai scrivendo a')
        set_text('groupName', '\nNome gruppo: ')
        set_text('supergroupName', '\nNome supergruppo: ')
        set_text('users', '\nUtenti: ')
        set_text('admins', '\nAdmins: ')
        set_text('kickedUsers', '\nUtenti rimossi: ')
        set_text('userInfo', 'Info utente:')
        set_text('peerTypeUnknown', 'Tipo sconosciuto.')
        set_text('ishereYes', 'Si.')
        set_text('ishereNo', 'No.')

        -- ingroup.lua --
        set_text('welcomeNewRealm', 'Benvenuto nel tuo nuovo regno.')
        set_text('realmIs', 'Questo è un regno.')
        set_text('realmAdded', 'Il regno è stato aggiunto.')
        set_text('realmAlreadyAdded', 'Il regno è già stato aggiunto.')
        set_text('realmRemoved', 'Il regno è stato rimosso.')
        set_text('realmNotAdded', 'Regno non aggiunto.')
        set_text('errorAlreadyRealm', 'Errore, è già un regno.')
        set_text('errorNotRealm', 'Errore, non è un regno.')
        set_text('promotedOwner', 'Sei stato promosso a proprietario.')
        set_text('groupIs', 'Questo è un gruppo.')
        set_text('groupAlreadyAdded', 'Il gruppo è già stato aggiunto.')
        set_text('groupAddedOwner', 'Il gruppo è stato aggiunto e tu promosso a proprietario.')
        set_text('groupRemoved', 'Il gruppo è stato rimosso.')
        set_text('groupNotAdded', 'Gruppo non aggiunto.')
        set_text('errorAlreadyGroup', 'Errore, è già un gruppo.')
        set_text('errorNotGroup', 'Errore, non è un gruppo.')
        set_text('noAutoDemote', 'Non puoi degradarti da solo.')

        -- inpm.lua --
        set_text('none', 'Nessuno')
        set_text('groupsJoin', 'Gruppi:\nUsa /join <group_id> per entrare\n\n')
        set_text('realmsJoin', 'Reami:\nUsa /join <realm_id> per entrare\n\n')
        set_text('youGbanned', 'Sei bannato globalmente.')
        set_text('youBanned', 'Sei bannato.')
        set_text('chatNotFound', 'Chat non trovata.')
        set_text('privateGroup', 'Gruppo privato.')
        set_text('addedTo', 'Sei stato aggiunto a: ')
        set_text('supportAdded', 'Aggiunto membro di supporto ')
        set_text('adminAdded', 'Aggiunto admin ')
        set_text('toChat', ' a 👥 ')
        set_text('aliasSaved', 'Alias salvato.')
        set_text('aliasDeleted', 'Alias eliminato.')
        set_text('noAliasFound', 'Nessun gruppo trovato con quell\'alias.')

        -- inrealm.lua --
        set_text('realm', 'Regno ')
        set_text('group', 'Gruppo ')
        set_text('created', ' creato.')
        set_text('chatTypeNotFound', 'Tipo chat non trovato.')
        set_text('usersIn', 'Utenti in ')
        set_text('alreadyAdmin', ' è già un admin.')
        set_text('promoteAdmin', ' è stato promosso ad admin.')
        set_text('notAdmin', ' non è un admin.')
        set_text('demoteAdmin', ' è stato degradato da admin.')
        set_text('groupListStart', 'Gruppi:\n')
        set_text('noRealms', 'Nessun regno al momento.')
        set_text('realmListStart', 'Reami:\n')
        set_text('inGroup', ' in questo gruppo')
        set_text('supportRemoved', ' è stato rimosso dal team di supporto.')
        set_text('supportAdded', ' è stato aggiunto al team di supporto.')
        set_text('logAlreadyYes', 'Gruppo di log già abilitato.')
        set_text('logYes', 'Gruppo di log abilitato.')
        set_text('logAlreadyNo', 'Gruppo di log già disabilitato.')
        set_text('logNo', 'Gruppo di log disabilitato.')
        set_text('descriptionSet', 'Descrizione settata per: ')
        set_text('errorGroup', 'Errore, gruppo ')
        set_text('errorRealm', 'Errore, regno ')
        set_text('notFound', ' non trovato')
        set_text('chat', 'Chat ')
        set_text('removed', ' rimossa')
        set_text('groupListCreated', 'Lista gruppi creata.')
        set_text('realmListCreated', 'Lista reami creata.')

        -- invite.lua --
        set_text('userBanned', 'L\'utente è bannato.')
        set_text('userGbanned', 'L\'utente è bannato globalmente.')
        set_text('privateGroup', 'Il gruppo è privato.')

        --[[
        -- knivesgame.lua --
        set_text('knivesAlreadySignedUp', 'Sei già registrato, usa /ruleta per morire.')
        set_text('knivesSignedUp', 'Sei stato registrato, have a nice death.')
        set_text('knivesDeleted', 'Sei stato eliminato dalla ruleta.')
        set_text('knivesRequireSignUp', 'Prima di morire devi registrarti, usa /registerme.')
        set_text('knivesGroupDeleted', 'Gruppo disabilitato per ruleta.')
        set_text('knivesRequirePoints', 'Richiede almeno 11 punti.')
        set_text('knivesRequireZeroPoints', 'Non puoi eliminarti se sei in negativo col punteggio.')
        set_text('roundsLeft', 'Round rimasti: ')
        set_text('shotsLeft', 'Colpi rimasti: ')
        set_text('capsChanged', 'Proiettili nella pistola: ')
        set_text('challengeCapsChanged', 'Proiettili nella pistola da sfida: ')
        set_text('cylinderChanged', 'Nuovo tamburo da: ')
        set_text('challengeCylinderChanged', 'Nuovo tamburo sfida da: ')
        set_text('errorCapsRange', 'Errore, il range è [1-X].')
        set_text('errorCylinderRange', 'Errore, il range è [5-10].')
        set_text('cylinderCapacity', 'Capienza tamburo: ')
        set_text('challengeCylinderCapacity', 'Capienza tamburo sfida: ')
        set_text('capsNumber', 'Proiettili: ')
        set_text('challengeCapsNumber', 'Proiettili sfida: ')
        set_text('forwardingRuleta', 'L\'inoltro dei messaggi su ruleta non è consentito.')
        set_text('ruletaDeathPercentage', 'Le probabilità di morire sono del ')
        ]]

        -- locks --
        set_text('nameLock', '\nBlocco nome: ')
        set_text('nameAlreadyLocked', 'Nome gruppo già bloccato.')
        set_text('nameLocked', 'Nome gruppo bloccato.')
        set_text('nameAlreadyUnlocked', 'Nome gruppo già sbloccato.')
        set_text('nameUnlocked', 'Nome gruppo sbloccato.')
        set_text('photoLock', '\nBlocco foto: ')
        set_text('photoAlreadyLocked', 'Foto gruppo già bloccata.')
        set_text('photoLocked', 'Foto gruppo bloccata.')
        set_text('photoAlreadyUnlocked', 'Foto gruppo già sbloccata.')
        set_text('photoUnlocked', 'Foto gruppo sbloccata.')
        set_text('membersLock', '\nBlocco membri: ')
        set_text('membersAlreadyLocked', 'Membri gruppo già bloccati.')
        set_text('membersLocked', 'Membri gruppo bloccati.')
        set_text('membersAlreadyUnlocked', 'Membri gruppo già sbloccati.')
        set_text('membersUnlocked', 'Membri gruppo sbloccati.')
        set_text('leaveLock', '\nBlocco abbandono: ')
        set_text('leaveAlreadyLocked', 'Uscita già punita col ban.')
        set_text('leaveLocked', 'Uscita punita col ban.')
        set_text('leaveAlreadyUnlocked', 'Uscita già consentita.')
        set_text('leaveUnlocked', 'Uscita consentita.')
        set_text('spamLock', '\nBlocco spam: ')
        set_text('spamAlreadyLocked', 'Spam già vietato.')
        set_text('spamLocked', 'Spam vietato.')
        set_text('spamAlreadyUnlocked', 'Spam già consentito.')
        set_text('spamUnlocked', 'Spam consentito.')
        set_text('floodSensibility', '\nSensibilità flood: ')
        set_text('floodUnlockOwners', 'Solo i proprietari possono sbloccare il flood.')
        set_text('floodLock', '\nBlocco flood: ')
        set_text('floodAlreadyLocked', 'Flood già bloccato.')
        set_text('floodLocked', 'Flood bloccato.')
        set_text('floodAlreadyUnlocked', 'Flood già sbloccato.')
        set_text('floodUnlocked', 'Flood sbloccato.')
        set_text('arabicLock', '\nBlocco arabo: ')
        set_text('arabicAlreadyLocked', 'Arabo già vietato.')
        set_text('arabicLocked', 'Arabo vietato.')
        set_text('arabicAlreadyUnlocked', 'Arabo già consentito.')
        set_text('arabicUnlocked', 'Arabo consentito.')
        set_text('botsLock', '\nBlocco bot: ')
        set_text('botsAlreadyLocked', 'Bots già vietati.')
        set_text('botsLocked', 'Bots vietati.')
        set_text('botsAlreadyUnlocked', 'Bots già consentiti.')
        set_text('botsUnlocked', 'Bots consentiti.')
        set_text('linksLock', '\nBlocco link: ')
        set_text('linksAlreadyLocked', 'Link già vietati.')
        set_text('linksLocked', 'Link vietati.')
        set_text('linksAlreadyUnlocked', 'Link già consentiti.')
        set_text('linksUnlocked', 'Link consentiti.')
        set_text('rtlLock', '\nBlocco RTL: ')
        set_text('rtlAlreadyLocked', 'Caratteri RTL già vietati.')
        set_text('rtlLocked', 'Caratteri RTL vietati.')
        set_text('rtlAlreadyUnlocked', 'Caratteri RTL già consentiti.')
        set_text('rtlUnlocked', 'Caratteri RTL consentiti.')
        set_text('tgserviceLock', '\nBlocco messaggi di servizio: ')
        set_text('tgserviceAlreadyLocked', 'Messaggi di servizio già bloccati.')
        set_text('tgserviceLocked', 'Messaggi di servizio bloccati.')
        set_text('tgserviceAlreadyUnlocked', 'Messaggi di servizio già sbloccati.')
        set_text('tgserviceUnlocked', 'Messaggi di servizio sbloccati.')
        set_text('stickersLock', '\nBlocco stickers: ')
        set_text('stickersAlreadyLocked', 'Stickers già vietati.')
        set_text('stickersLocked', 'Stickers vietati.')
        set_text('stickersAlreadyUnlocked', 'Stickers già consentiti.')
        set_text('stickersUnlocked', 'Stickers consentiti.')
        set_text('public', '\nPubblico: ')
        set_text('publicAlreadyYes', 'Gruppo già pubblico.')
        set_text('publicYes', 'Gruppo pubblico.')
        set_text('publicAlreadyNo', 'Gruppo già privato.')
        set_text('publicNo', 'Gruppo privato.')
        set_text('contactsAlreadyLocked', 'Condivisione contatti già vietata.')
        set_text('contactsLocked', 'Condivisione contatti vietata.')
        set_text('contactsAlreadyUnlocked', 'Condivisione contatti già consentita.')
        set_text('contactsUnlocked', 'Condivisione contatti consentita.')
        set_text('strictrules', '\nPugno di ferro: ')
        set_text('strictrulesAlreadyLocked', 'Pugno di ferro già attivato.')
        set_text('strictrulesLocked', 'Pugno di ferro attivato.')
        set_text('strictrulesAlreadyUnlocked', 'Pugno di ferro già disattivato.')
        set_text('strictrulesUnlocked', 'Pugno di ferro disattivato.')

        -- onservice.lua --
        set_text('notMyGroup', 'Questo non è un mio gruppo, addio.')

        -- plugins.lua --
        set_text('enabled', ' abilitato.')
        set_text('disabled', ' disabilitato.')
        set_text('alreadyEnabled', ' già abilitato.')
        set_text('alreadyDisabled', ' già disabilitato.')
        set_text('notExists', ' non esiste.')
        set_text('systemPlugin', '⛔️ Non è possibile disabilitare questo plugin in quanto è necessario per il corretto funzionamento del sistema.')
        set_text('disabledOnChat', ' disabilitato su questa chat.')
        set_text('noDisabledPlugin', '❔ Nessun plugin disabilitato su questa chat.')
        set_text('pluginNotDisabled', '✔️ Questo plugin non è disabilitato su questa chat.')
        set_text('pluginEnabledAgain', ' nuovamente abilitato.')
        set_text('pluginsReloaded', '💊 Plugins ricaricati.')

        -- pokedex.lua --
        set_text('noPoke', 'Nessun pokémon trovato.')
        set_text('pokeName', 'Nome: ')
        set_text('pokeWeight', 'Peso: ')
        set_text('pokeHeight', 'Altezza: ')

        -- ruletagame.lua --
        set_text('ruletaAlreadySignedUp', 'Sei già registrato, usa /ruleta per morire.')
        set_text('ruletaSignedUp', 'Sei stato registrato, have a nice death.')
        set_text('ruletaDeleted', 'Sei stato eliminato dalla ruleta.')
        set_text('ruletaRequireSignUp', 'Prima di morire devi registrarti, usa /registerme.')
        set_text('ruletaGroupDeleted', 'Gruppo disabilitato per ruleta.')
        set_text('ruletaRequirePoints', 'Richiede almeno 11 punti.')
        set_text('ruletaRequireZeroPoints', 'Non puoi eliminarti se sei in negativo col punteggio.')
        set_text('roundsLeft', 'Round rimasti: ')
        set_text('shotsLeft', 'Colpi rimasti: ')
        set_text('capsChanged', 'Proiettili nella pistola: ')
        set_text('challengeCapsChanged', 'Proiettili nella pistola da sfida: ')
        set_text('cylinderChanged', 'Nuovo tamburo da: ')
        set_text('challengeCylinderChanged', 'Nuovo tamburo sfida da: ')
        set_text('errorCapsRange', 'Errore, il range è [1-X].')
        set_text('errorCylinderRange', 'Errore, il range è [5-10].')
        set_text('cylinderCapacity', 'Capienza tamburo: ')
        set_text('challengeCylinderCapacity', 'Capienza tamburo sfida: ')
        set_text('capsNumber', 'Proiettili: ')
        set_text('challengeCapsNumber', 'Proiettili sfida: ')
        set_text('forwardingRuleta', 'L\'inoltro dei messaggi su ruleta non è consentito.')
        set_text('ruletaDeathPercentage', 'Le probabilità di morire sono del ')

        -- set.lua --
        set_text('saved', ' salvato.')
        set_text('sendMedia', 'Mandami il media che vuoi salvare (audio o foto).')
        set_text('cancelled', 'Annullato.')
        set_text('nothingToSet', 'Niente da salvare.')
        set_text('mediaSaved', 'Media salvato.')

        -- spam.lua --
        set_text('msgSet', 'Messaggio impostato.')
        set_text('msgsToSend', 'Messaggi da mandare: ')
        set_text('timeBetweenMsgs', 'Tempo tra ogni messaggio: X secondi.')
        set_text('msgNotSet', 'Non hai impostato il messaggio, usa /setspam.')

        -- stats.lua --
        set_text('usersInChat', 'Utenti in questa chat\n')
        set_text('totalChatMessages', 'Messaggi totali della chat: ')
        set_text('groups', '\nGruppi: ')
        set_text('statsCleaned', 'Statistiche azzerate.')

        -- strings.lua --
        set_text('langUpdate', 'ℹ️ Stringhe aggiornate.')

        -- supergroup.lua --
        set_text('makeBotAdmin', 'Promuovimi prima amministratrice!')
        set_text('groupIs', 'Questo è un gruppo.')
        set_text('supergroupAlreadyAdded', 'Il supergruppo è già stato aggiunto.')
        set_text('errorAlreadySupergroup', 'Errore, è già un supergruppo.')
        set_text('supergroupAdded', 'Il supergruppo è stato aggiunto.')
        set_text('supergroupRemoved', 'Il supergruppo è stato rimosso.')
        set_text('supergroupNotAdded', 'Supergruppo non aggiunto.')
        set_text('membersOf', 'Membri di ')
        set_text('membersKickedFrom', 'Membri rimossi da ')
        set_text('cantKickOtherAdmin', 'Non puoi rimuovere altri amministratori.')
        set_text('promoteSupergroupMod', ' è stato promosso ad amministratore (telegram).')
        set_text('demoteSupergroupMod', ' è stato degradato da amministratore (telegram).')
        set_text('alreadySupergroupMod', ' è già un amministratore (telegram).')
        set_text('notSupergroupMod', ' non è un amministratore (telegram).')
        set_text('cantDemoteOtherAdmin', 'Non puoi degradare altri amministratori.')
        set_text('leftKickme', 'Uscito tramite /kickme.')
        set_text('setOwner', ' ora è l\'owner.')
        set_text('inThisSupergroup', ' in questo supergruppo.')
        set_text('linkSaved', 'Nuovo link impostato.')
        set_text('supergroupUsernameChanged', 'Username supergruppo cambiato.')
        set_text('errorChangeUsername', 'Errore nell\'impostare l\'username.\nPotrebbe già essere in uso.\n\nPuoi usare lettere numeri e l\'underscore.\nLunghezza minima 5 caratteri.')
        set_text('usernameCleaned', 'Username gruppo pulito.')
        set_text('errorCleanedUsername', 'Errore nel tentativo di pulire l\'username.')

        -- unset.lua --
        set_text('deleted', ' eliminato.')

        -- warn.lua --
        set_text('errorWarnRange', 'Errore, il range è [0-10].')
        set_text('warnSet', 'Il warn è stato impostato a ')
        set_text('neverWarn', 'Gli avvertimenti non funzioneranno più.')
        set_text('noWarnSet', 'Il warn non è ancora stato impostato.')
        set_text('cantWarnHigher', 'Non puoi avvertire un mod/owner/admin/sudo!')
        set_text('warned', 'Sei stato avvertito X volte, datti una regolata!')
        set_text('unwarned', 'Ti è stato tolto un avvertimento, continua così!')
        set_text('alreadyZeroWarnings', 'Sei già a zero avvertimenti.')
        set_text('zeroWarnings', 'I tuoi avvertimenti sono stati azzerati.')
        set_text('yourWarnings', 'Sei a quota X avvertimenti su un massimo di Y.')

        -- whitelist.lua --
        set_text('userBot', 'Utente/Bot ')
        set_text('whitelistRemoved', ' rimosso dalla whitelist.')
        set_text('whitelistAdded', ' aggiunto alla whitelist.')
        set_text('whitelistCleaned', 'Whitelist svuotata.')

        ------------
        -- Usages --
        ------------
        -- administrator.lua --
        set_text('administrator:0', 21)
        set_text('administrator:1', '🅿️ ADMINISTRATOR')
        set_text('administrator:2', 'ADMIN')
        set_text('administrator:3', '(#pm|sasha messaggia) <user_id> <msg>: Sasha invia <msg> a <user_id>.')
        set_text('administrator:4', '#import <group_link>: Sasha entra nel gruppo tramite <group_link>.')
        set_text('administrator:5', '(#block|sasha blocca) <user_id>: Sasha blocca <user_id>.')
        set_text('administrator:6', '(#unblock|sasha sblocca) <user_id>: Sasha sblocca <user_id>.')
        set_text('administrator:7', '(#markread|sasha segna letto) (on|off): Sasha segna come [non] letti i messaggi ricevuti.')
        set_text('administrator:8', '(#setbotphoto|sasha cambia foto): Sasha chiede la foto da settare come profilo.')
        set_text('administrator:9', '(#updateid|sasha aggiorna longid): Sasha salva il long_id.')
        set_text('administrator:10', '(#addlog|sasha aggiungi log): Sasha aggiunge il log.')
        set_text('administrator:11', '(#remlog|sasha rimuovi log): Sasha rimuove il log.')
        set_text('administrator:12', 'SUDO')
        set_text('administrator:13', '(#contactlist|sasha lista contatti) (txt|json): Sasha manda la lista dei contatti.')
        set_text('administrator:14', '(#dialoglist|sasha lista chat) (txt|json): Sasha manda la lista delle chat.')
        set_text('administrator:15', '(#addcontact|sasha aggiungi contatto) <phone> <name> <surname>: Sasha aggiunge il contatto specificato.')
        set_text('administrator:16', '(#delcontact|sasha elimina contatto) <user_id>: Sasha elimina il contatto <user_id>.')
        set_text('administrator:17', '(#sendcontact|sasha invia contatto) <phone> <name> <surname>: Sasha invia il contatto specificato.')
        set_text('administrator:18', '(#mycontact|sasha mio contatto): Sasha invia il contatto del richiedente.')
        set_text('administrator:19', '(#sync_gbans|sasha sincronizza superban): Sasha sincronizza la lista dei superban con quella offerta da TeleSeed.')
        set_text('administrator:20', '(#backup|sasha esegui backup): Sasha esegue un backup di se stessa e invia il log al richiedente.')
        set_text('administrator:21', '#vardump [<reply>|<msg_id>]: Sasha esegue il vardump del messaggio specificato.')

        -- anti_spam.lua --
        set_text('anti_spam:0', 2)
        set_text('anti_spam:1', '🅿️ ANTI_SPAM')
        set_text('anti_spam:2', 'Sasha rimuove l\'utente che spamma oltre al massimo consentito.')

        -- apod.lua --
        set_text('apod:0', 5)
        set_text('apod:1', '🅿️ APOD')
        set_text('apod:2', '#apod|#astro [<date>]: Sasha manda l\'APOD.')
        set_text('apod:3', '(#apod|#astro)hd [<date>]: Sasha manda l\'APOD in HD.')
        set_text('apod:4', '(#apod|#astro)text [<date>]: Sasha manda la spiegazione dell\'APOD.')
        set_text('apod:5', 'Se c\'è <date> ed è nel formato AAAA-MM-GG l\'APOD è di <date>.')

        -- arabic_lock.lua --
        set_text('arabic_lock:0', 2)
        set_text('arabic_lock:1', '🅿️ ARABIC_LOCK')
        set_text('arabic_lock:2', 'Sasha blocca l\'arabo nei gruppi.')

        -- banhammer.lua --
        set_text('banhammer:0', 17)
        set_text('banhammer:1', '🅿️ BANHAMMER')
        set_text('banhammer:2', '(#kickme|sasha uccidimi): Sasha rimuove l\'utente.')
        set_text('banhammer:3', 'MOD')
        set_text('banhammer:4', '(#kick|spara|[sasha] uccidi) <id>|<username>|<reply>|from: Sasha rimuove l\'utente specificato.')
        set_text('banhammer:5', '(#ban|esplodi|kaboom|[sasha] banna|[sasha] decompila) <id>|<username>|<reply>|from: Sasha banna l\'utente specificato e lo rimuove, se tenta di rientrare viene nuovamente rimosso.')
        set_text('banhammer:6', '(#unban|[sasha] sbanna|[sasha] [ri]compila) <id>|<username>|<reply>|from: Sasha sbanna l\'utente specificato.')
        set_text('banhammer:7', '(#banlist|[sasha] lista ban): Sasha mostra la lista di utenti bannati dal gruppo.')
        set_text('banhammer:8', '(#kickrandom|sasha uccidi random|spara random): Sasha sceglie un utente a caso e lo rimuove.')
        set_text('banhammer:9', 'OWNER')
        set_text('banhammer:10', '(#kicknouser|sasha uccidi nouser|spara nouser): Sasha rimuove gli utenti senza username.')
        set_text('banhammer:11', '(#kickinactive [<msgs>]|((sasha uccidi)|spara sotto <msgs> messaggi)): Sasha rimuove tutti gli utenti inattivi sotto <msgs> messaggi.')
        set_text('banhammer:12', 'SUPPORT')
        set_text('banhammer:13', '(#gban|[sasha] superbanna) <id>|<username>|<reply>|from: Sasha superbanna l\'utente specificato e lo rimuove, se tenta di rientrare viene nuovamente rimosso.')
        set_text('banhammer:14', '(#ungban|[sasha] supersbanna) <id>|<username>|<reply>|from: Sasha supersbanna l\'utente specificato.')
        set_text('banhammer:15', '(#gbanlist|[sasha] lista superban): Sasha mostra la lista di utenti super bannati.')
        set_text('banhammer:16', 'ADMIN')
        set_text('banhammer:17', '(#banlist|[sasha] lista ban) <group_id>: Sasha mostra la lista di utenti bannati da <group_id>.')

        -- bot.lua --
        set_text('bot:0', 5)
        set_text('bot:1', '🅿️ BOT')
        set_text('bot:2', 'OWNER')
        set_text('bot:3', '#bot|sasha on|off: Sasha si attiva|disattiva.')
        set_text('bot:4', 'ADMIN')
        set_text('bot:5', '#bot|sasha <group_id> on|off: Sasha si attiva|disattiva nel gruppo specificato.')

        -- botinteract.lua --
        set_text('botinteract:0', 9)
        set_text('botinteract:1', '🅿️ BOTINTERACT')
        set_text('botinteract:2', '#getchar: Sasha manda i caratteri necessari per l\'interazione con i bot.')
        set_text('botinteract:3', '$<text>: Sasha manda <text> al bot.')
        set_text('botinteract:4', '#sendmedia: Sasha manderà il media che verrà inviato nella chat al bot.')
        set_text('botinteract:5', '#undo: Sasha annulla il comando sendmedia.')
        set_text('botinteract:6', 'MOD')
        set_text('botinteract:7', '#unsetbot <username>: Sasha smetterà di interagire con <username>.')
        set_text('botinteract:8', 'ADMIN')
        set_text('botinteract:9', '#setbot <username>: Sasha interagirà con <username>.')

        -- broadcast.lua --
        set_text('broadcast:0', 5)
        set_text('broadcast:1', '🅿️ BROADCAST')
        set_text('broadcast:2', 'ADMIN')
        set_text('broadcast:3', '#br <group_id> <text>: Sasha invia <text> a <group_id>.')
        set_text('broadcast:4', 'SUDO')
        set_text('broadcast:5', '#broadcast <text>: Sasha invia <text> a tutti i gruppi.')

        -- codify.lua --
        set_text('codify:0', 3)
        set_text('codify:1', '🅿️ CODIFY')
        set_text('codify:2', 'MOD')
        set_text('codify:3', '#codify <text>|<reply>: Sasha manda <text> o il messaggio specificato in forma di codice.')

        -- dogify.lua --
        set_text('dogify:0', 2)
        set_text('dogify:1', '🅿️ DOGIFY')
        set_text('dogify:2', '(#dogify|[sasha] doge) <your/words/with/slashes>: Sasha crea un\'immagine col doge e le parole specificate.')

        -- duckduckgo.lua --
        set_text('duckduckgo:0', 2)
        set_text('duckduckgo:1', '🅿️ DUCKDUCKGO')
        set_text('duckduckgo:2', '#duck[duck]go <terms>: Sasha cerca <terms> su DuckDuckGo.')

        -- echo.lua --
        set_text('echo:0', 3)
        set_text('echo:1', '🅿️ ECHO')
        set_text('echo:2', 'MOD')
        set_text('echo:3', '(#echo|sasha ripeti) <text>: Sasha ripete <text>.')

        -- feedback.lua --
        set_text('feedback:0', 2)
        set_text('feedback:1', '🅿️ FEEDBACK')
        set_text('feedback:2', '#feedback <text>: Sasha invia <text> al suo creatore.')

        -- filemanager.lua --
        set_text('filemanager:0', 16)
        set_text('filemanager:1', '🅿️ FILEMANAGER')
        set_text('filemanager:2', 'SUDO')
        set_text('filemanager:3', '#folder: Sasha manda la directory attuale.')
        set_text('filemanager:4', '#cd [<directory>]: Sasha entra in <directory>, se non è specificata torna alla cartella base.')
        set_text('filemanager:5', '#ls: Sasha manda la lista di file e cartelle della directory corrente.')
        set_text('filemanager:6', '#mkdir <directory>: Sasha crea <directory>.')
        set_text('filemanager:7', '#rmdir <directory>: Sasha elimina <directory>.')
        set_text('filemanager:8', '#rm <file>: Sasha elimina <file>.')
        set_text('filemanager:9', '#touch <file>: Sasha crea <file>.')
        set_text('filemanager:10', '#cat <file>: Sasha manda il contenuto di <file>.')
        set_text('filemanager:11', '#tofile <file> <text>: Sasha crea <file> con <text> come contenuto.')
        set_text('filemanager:12', '#shell <command>: Sasha esegue <command>.')
        set_text('filemanager:13', '#cp <file> <directory>: Sasha copia <file> in <directory>.')
        set_text('filemanager:14', '#mv <file> <directory>: Sasha sposta <file> in <directory>.')
        set_text('filemanager:15', '#upload <file>: Sasha manda <file> nella chat.')
        set_text('filemanager:16', '#download <reply>: Sasha scarica il file contenuto in <reply>.')

        -- flame.lua --
        set_text('flame:0', 5)
        set_text('flame:1', '🅿️ FLAME')
        set_text('flame:2', 'MOD')
        set_text('flame:3', '(#startflame|[sasha] flamma) <id>|<username>|<reply>: Sasha flamma l\'utente specificato.')
        set_text('flame:4', '(#stopflame|[sasha] stop flame): Sasha smette di flammare.')
        set_text('flame:5', '(#flameinfo|[sasha] info flame): Sasha manda le info su chi sta flammando.')

        -- get.lua --
        set_text('get:0', 3)
        set_text('get:1', '🅿️ GET')
        set_text('get:2', '(#getlist|#get|sasha lista): Sasha mostra una lista delle variabili settate.')
        set_text('get:3', '[#get] <var_name>: Sasha manda il valore di <var_name>.')

        -- goodbyewelcome.lua --
        set_text('goodbyewelcome:0', 10)
        set_text('goodbyewelcome:1', '🅿️ GOODBYEWELCOME')
        set_text('goodbyewelcome:2', '#getwelcome: Sasha manda il benvenuto.')
        set_text('goodbyewelcome:3', '#getgoodbye: Sasha manda l\'addio.')
        set_text('goodbyewelcome:4', 'MOD')
        set_text('goodbyewelcome:5', '#setwelcome <text>: Sasha imposta <text> come benvenuto.')
        set_text('goodbyewelcome:6', '#setgoodbye <text>: Sasha imposta <text> come addio.')
        set_text('goodbyewelcome:7', '#unsetwelcome: Sasha rimuove il benvenuto.')
        set_text('goodbyewelcome:8', '#unsetgoodbye: Sasha rimuove l\'addio.')
        set_text('goodbyewelcome:9', '#setmemberswelcome <value>: Sasha dopo <value> membri manderà il benvenuto con le regole, se zero il benvenuto non verrà più mandato.')
        set_text('goodbyewelcome:10', '#getmemberswelcome: Sasha manda il numero di membri entrati dopo i quali invia il benvenuto.')

        -- help.lua --
        set_text('help:0', 6)
        set_text('help:1', '🅿️ HELP')
        set_text('help:2', '(#sudolist|sasha lista sudo): Sasha manda la lista dei sudo.')
        set_text('help:3', '(#help|sasha aiuto): Sasha mostra una lista dei plugin disponibili.')
        set_text('help:4', '(#help|#commands|sasha aiuto) <plugin_name>|<plugin_number> [<fake_rank>]: Sasha mostra l\'aiuto per il plugin specificato.')
        set_text('help:5', '(#helpall|#allcommands|sasha aiuto tutto) [<fake_rank>]: Sasha mostra tutti i comandi di tutti i plugin.')
        set_text('help:6', 'Il parametro <fake_rank> serve per mandare l\'help di un rango più basso, i ranghi sono: USER, MOD, OWNER, SUPPORT, ADMIN, SUDO.')

        -- info.lua --
        set_text('info:0', 13)
        set_text('info:1', '🅿️ INFO')
        set_text('info:2', '#getrank|rango [<id>|<username>|<reply>]: Sasha manda il rank dell\'utente.')
        set_text('info:3', '(#info|[sasha] info): Sasha manda le info dell\'utente e della chat o di se stessa')
        set_text('info:4', '#ishere <id>|<username>: Sasha dice se l\'utente specificato è presente nel gruppo.')
        set_text('info:5', '(#groupinfo|[sasha] info gruppo): Sasha manda le info del gruppo.')
        set_text('info:6', 'MOD')
        set_text('info:7', '(#info|[sasha] info) <id>|<username>|<reply>|from: Sasha manda le info dell\'utente specificato.')
        set_text('info:8', '(#who|#members|[sasha] lista membri): Sasha manda la lista degli utenti.')
        set_text('info:9', '(#kicked|[sasha] lista rimossi): Sasha manda la lista degli utenti rimossi.')
        set_text('info:10', 'ADMIN')
        set_text('info:11', '(#groupinfo|[sasha] info gruppo) <group_id>: Sasha manda le info del gruppo specificato.')
        set_text('info:12', 'SUDO')
        set_text('info:13', '(#database|[sasha] database): Sasha salva i dati di tutti gli utenti.')

        -- ingroup.lua --
        set_text('ingroup:0', 33)
        set_text('ingroup:1', '🅿️ INGROUP')
        set_text('ingroup:2', '(#rules|sasha regole): Sasha mostra le regole del gruppo.')
        set_text('ingroup:3', '(#about|sasha descrizione): Sasha mostra la descrizione del gruppo.')
        set_text('ingroup:4', '(#modlist|[sasha] lista mod): Sasha mostra la lista dei moderatori.')
        set_text('ingroup:5', '#owner: Sasha mostra l\'id del proprietario del gruppo.')
        set_text('ingroup:6', 'MOD')
        set_text('ingroup:7', '#setname|#setgpname <group_name>: Sasha imposta il nome del gruppo con <group_name>.')
        set_text('ingroup:8', '#setphoto|#setgpphoto: Sasha imposta e blocca la foto del gruppo.')
        set_text('ingroup:9', '(#setrules|sasha imposta regole) <text>: Sasha imposta <text> come regole.')
        set_text('ingroup:10', '(#setabout|sasha imposta descrizione) <text>: Sasha imposta <text> come descrizione.')
        set_text('ingroup:11', '(#lock|[sasha] blocca) name|member|photo|flood|arabic|bots|leave|links|rtl|sticker|contacts: Sasha blocca l\'opzione specificata.')
        set_text('ingroup:12', '(#unlock|[sasha] sblocca) name|member|photo|flood|arabic|bots|leave|links|rtl|sticker|contacts: Sasha sblocca l\'opzione specificata.')
        set_text('ingroup:13', '#muteuser|voce <id>|<username>|<reply>|from: Sasha imposta|toglie il muto sull\'utente.')
        set_text('ingroup:14', '(#muteslist|lista muti): Sasha manda la lista delle variabili mute della chat.')
        set_text('ingroup:15', '(#mutelist|lista utenti muti): Sasha manda la lista degli utenti muti della chat.')
        set_text('ingroup:16', '#settings: Sasha mostra le impostazioni del gruppo.')
        set_text('ingroup:17', '#public yes|no: Sasha imposta il gruppo come pubblico|privato.')
        set_text('ingroup:18', '(#newlink|sasha crea link): Sasha crea il link del gruppo.')
        set_text('ingroup:19', '(#link|sasha link): Sasha mostra il link del gruppo.')
        set_text('ingroup:20', '#setflood <value>: Sasha imposta il flood massimo del gruppo a <value>.')
        set_text('ingroup:21', 'OWNER')
        set_text('ingroup:22', '(#setlink|[sasha] imposta link) <link>: Sasha imposta <link> come link d\'invito.')
        set_text('ingroup:23', '(#promote|[sasha] promuovi) <username>|<reply>: Sasha promuove a moderatore l\'utente specificato.')
        set_text('ingroup:24', '(#demote|[sasha] degrada) <username>|<reply>: Sasha degrada l\'utente specificato.')
        set_text('ingroup:25', '#mute|silenzia all|text|documents|gifs|video|photo|audio: Sasha imposta il muto sulla variabile specificata.')
        set_text('ingroup:26', '#unmute|ripristina all|text|documents|gifs|video|photo|audio: Sasha rimuove il muto sulla variabile specificata.')
        set_text('ingroup:27', '#setowner <id>|<reply>: Sasha imposta l\'utente specificato come proprietario.')
        set_text('ingroup:28', '#clean modlist|rules|about: Sasha pulisce il parametro specificato.')
        set_text('ingroup:29', 'ADMIN')
        set_text('ingroup:30', '#add [realm]: Sasha aggiunge il gruppo|regno.')
        set_text('ingroup:31', '#rem [realm]: Sasha rimuove il gruppo|regno.')
        set_text('ingroup:32', '#kill group|realm: Sasha elimina ogni utente nel gruppo|regno e poi lo chiude.')
        set_text('ingroup:33', '#setgpowner <group_id> <user_id>: Sasha imposta <user_id> come proprietario.')

        -- inpm.lua --
        set_text('inpm:0', 11)
        set_text('inpm:1', '🅿️ INPM')
        set_text('inpm:2', '#chats: Sasha mostra un elenco di chat "pubbliche".')
        set_text('inpm:3', '#chatlist: Sasha manda un file con un elenco di chat "pubbliche".')
        set_text('inpm:4', 'ADMIN')
        set_text('inpm:5', '(#join|#inviteme|[sasha] invitami) <chat_id>|<alias> [support]: Sasha tenta di aggiungere l\'utente a <chat_id>|<alias>.')
        set_text('inpm:6', '#getaliaslist: Sasha manda la lista degli alias.')
        set_text('inpm:7', 'SUDO')
        set_text('inpm:8', '#allchats: Sasha mostra l\'elenco delle chat.')
        set_text('inpm:9', '#allchatlist: Sasha manda un file con l\'elenco delle chat.')
        set_text('inpm:10', '#setalias <alias> <group_id>: Sasha imposta <alias> come alias di <group_id>.')
        set_text('inpm:11', '#unsetalias <alias>: Sasha elimina <alias>.')

        -- inrealm.lua --
        set_text('inrealm:0', 28)
        set_text('inrealm:1', '🅿️ INREALM')
        set_text('inrealm:2', 'MOD')
        set_text('inrealm:3', '#who: Sasha mostra una lista di membri del gruppo/regno.')
        set_text('inrealm:4', '#wholist: Sasha invia un file con una lista di membri del gruppo/regno.')
        set_text('inrealm:5', 'OWNER')
        set_text('inrealm:6', '#log: Sasha manda un file contenente il log del gruppo/regno.')
        set_text('inrealm:7', 'ADMIN')
        set_text('inrealm:8', '(#creategroup|sasha crea gruppo) <group_name>: Sasha crea un gruppo col nome specificato.')
        set_text('inrealm:9', '(#createsuper|sasha crea supergruppo) <group_name>: Sasha crea un supergruppo col nome specificato.')
        set_text('inrealm:10', '(#createrealm|sasha crea regno) <realm_name>: Sasha crea un regno col nome specificato.')
        set_text('inrealm:11', '(#setabout|sasha imposta descrizione) <group_id> <text>: Sasha cambia la descrizione di <group_id> in <text>.')
        set_text('inrealm:12', '(#setrules|sasha imposta regole) <group_id> <text>: Sasha cambia le regole di <group_id> in <text>.')
        set_text('inrealm:13', '#setname <realm_name>: Sasha cambia il nome del regno in <realm_name>.')
        set_text('inrealm:14', '#setname|#setgpname <group_id> <group_name>: Sasha cambia il nome di <group_id> in <group_name>.')
        set_text('inrealm:15', '(#lock|[sasha] blocca) <group_id> name|member|photo|flood|arabic|links|spam|rtl|sticker: Sasha blocca l\'impostazione specificata di <group_id>.')
        set_text('inrealm:16', '(#unlock|[sasha] sblocca) <group_id> name|member|photo|flood|arabic|links|spam|rtl|sticker: Sasha sblocca l\'impostazione specificata di <group_id>.')
        set_text('inrealm:17', '#settings <group_id>: Sasha manda le impostazioni di <group_id>.')
        set_text('inrealm:18', '#type: Sasha mostra il tipo del gruppo.')
        set_text('inrealm:21', '#kill group|supergroup|realm <group_id>: Sasha rimuove tutti i membri di <group_id> e <group_id>.')
        set_text('inrealm:22', '#rem <group_id>: Sasha rimuove il gruppo.')
        set_text('inrealm:23', '#support <user_id>|<username>: Sasha promuove l\'utente specificato a supporto.')
        set_text('inrealm:24', '#-support <user_id>|<username>: Sasha degrada l\'utente specificato.')
        set_text('inrealm:25', '#list admins|groups|realms: Sasha mostra una lista della variabile specificata.')
        set_text('inrealm:26', 'SUDO')
        set_text('inrealm:27', '#addadmin <user_id>|<username>: Sasha promuove l\'utente specificato ad amminstratore.')
        set_text('inrealm:28', '#removeadmin <user_id>|<username>: Sasha degrada l\'utente specificato.')

        -- interact.lua --
        set_text('interact:0', 2)
        set_text('interact:1', '🅿️ INTERACT')
        set_text('interact:2', 'Sasha interagisce con gli utenti.')

        -- invite.lua --
        set_text('invite:0', 3)
        set_text('invite:1', '🅿️ INVITE')
        -- set_text('invite:2','OWNER')
        set_text('invite:2', 'ADMIN')
        set_text('invite:3', '(#invite|[sasha] invita|[sasha] resuscita) <id>|<username>|<reply>: Sasha invita l\'utente specificato.')

        --[[
        -- knivesgame.lua --
        set_text('knivesgame:0', 22)
        set_text('knivesgame:1', '🅿️ KNIVESGAME')
        set_text('knivesgame:2', 'Knives by AISasha. Knives è il lancio dei coltelli, Sasha lancia i coltelli con una certa precisione, se ti centra sei fuori altrimenti rimani.')
        set_text('knivesgame:3', '#registerme|#registrami: Sasha registra l\'utente al gioco.')
        set_text('knivesgame:4', '#deleteme|#eliminami: Sasha elimina i dati dell\'utente.')
        set_text('knivesgame:5', '#knivesinfo: Sasha manda le informazioni di knives.')
        set_text('knivesgame:6', '#mystats|#punti: Sasha manda le statistiche dell\'utente.')
        set_text('knivesgame:7', '#knives: Sasha cerca di ucciderti.')
        set_text('knivesgame:8', '#challenge|#sfida <username>|<reply>: Sasha avvia una sfida tra il mittente e l\'utente specificato, il vincitore vincerà 20 punti mentre il perdente ne perderà 20.')
        set_text('knivesgame:9', '#accept|#accetta: Sasha conferma la sfida.')
        set_text('knivesgame:10', '#reject|#rifiuta: Sasha cancella la sfida, se la sfida è già stata avviata ed è cancellata da uno dei giocatori esso perde 20 punti e viene ucciso.')
        set_text('knivesgame:11', '#challengeinfo: Sasha manda le informazioni della sfida in corso.')
        set_text('knivesgame:12', '#leaderboard|#classifica [(attempts|tentativi)|(deaths|morti)|(streak|serie)|(challenges|sfide)|(victories|vittorie)|(defeats|sconfitte)]: Sasha manda la classifica del parametro specificato, se nulla è specificato manderà quella dei punteggi.')
        set_text('knivesgame:13', 'MOD')
        set_text('knivesgame:14', '#setaccuracy <value>: Sasha imposta la precisione a <value>.')
        set_text('knivesgame:15', '#setchallengeaccuracy <value>: Sasha imposta la precisione nelle sfide a <value>.')
        set_text('knivesgame:16', 'ADMIN')
        set_text('knivesgame:17', '(#registergroupknives|registra gruppo knives): Sasha abilita il gruppo a giocare a knives.')
        set_text('knivesgame:18', '(#deletegroup|elimina gruppo): Sasha disabilita il gruppo per knives.')
        set_text('knivesgame:19', 'SUDO')
        set_text('knivesgame:20', '#createknivesdb: Sasha crea il database di knives.')
        set_text('knivesgame:21', '#addpoints <id> <value>: Sasha aggiunge <value> punti all\'utente specificato.')
        set_text('knivesgame:22', '#rempoints <id> <value>: Sasha sottrae <value> punti all\'utente specificato.')
        ]]

        -- leave_ban.lua --
        set_text('leave_ban:0', 2)
        set_text('leave_ban:1', '🅿️ LEAVE_BAN')
        set_text('leave_ban:2', 'Sasha banna l\'utente che esce dal gruppo.')

        -- msg_checks.lua --
        set_text('msg_checks:0', 2)
        set_text('msg_checks:1', '🅿️ MSG_CHECKS')
        set_text('msg_checks:2', 'Sasha controlla i messaggi che riceve.')

        -- onservice.lua --
        set_text('onservice:0', 3)
        set_text('onservice:1', '🅿️ ONSERVICE')
        set_text('onservice:2', 'ADMIN')
        set_text('onservice:3', '(#leave|sasha abbandona) [<group_id>]: Sasha lascia il gruppo.')

        -- plugins.lua --
        set_text('plugins:0', 10)
        set_text('plugins:1', '🅿️ PLUGINS')
        set_text('plugins:2', 'OWNER')
        set_text('plugins:3', '(#disabledlist|([sasha] lista disabilitati|disattivati)): Sasha mostra una lista dei plugins disabilitati su questa chat.')
        set_text('plugins:4', '(#[plugin[s]] enable|[sasha] abilita|[sasha] attiva) <plugin> chat: Sasha riabilita <plugin> su questa chat.')
        set_text('plugins:5', '(#[plugin[s]] disable|[sasha] disabilita|[sasha] disattiva) <plugin> chat: Sasha disabilita <plugin> su questa chat.')
        set_text('plugins:6', 'SUDO')
        set_text('plugins:7', '(#plugins|[sasha] lista plugins): Sasha mostra una lista di tutti i plugins.')
        set_text('plugins:8', '(#[plugin[s]] enable|[sasha] abilita|[sasha] attiva) <plugin> [chat]: Sasha abilita <plugin>, se specificato solo su questa chat.')
        set_text('plugins:9', '(#[plugin[s]] disable|[sasha] disabilita|[sasha] disattiva) <plugin> [chat]: Sasha disabilita <plugin>, se specificato solo su questa chat.')
        set_text('plugins:10', '(#[plugin[s]] reload|[sasha] ricarica): Sasha ricarica tutti i plugins.')

        -- pokedex.lua --
        set_text('pokedex:0', 2)
        set_text('pokedex:1', '🅿️ POKEDEX')
        set_text('pokedex:2', '#pokedex|#pokemon <name>|<id>: Sasha cerca il pokémon specificato e ne invia le informazioni.')

        -- qr.lua --
        set_text('qr:0', 6)
        set_text('qr:1', '🅿️ QR')
        set_text('qr:2', '(#qr|sasha qr) ["<background_color>" "<data_color>"] <text>: Sasha crea il QR Code di <text>, se specificato colora il QR Code.')
        set_text('qr:3', 'I colori possono essere specificati come segue:')
        set_text('qr:4', 'Testo => red|green|blue|purple|black|white|gray.')
        set_text('qr:5', 'Notazione Esadecimale => ("a56729" è marrone).')
        set_text('qr:6', 'Notazione Decimale => ("255-192-203" è rosa).')

        -- reactions.lua --
        set_text('reactions:0', 3)
        set_text('reactions:1', '🅿️ REACTIONS')
        set_text('reactions:2', 'SUDO')
        set_text('reactions:3', '#writing on|off: Sasha (fa finta|smette di far finta) di scrivere.')

        -- ruletagame.lua --
        set_text('ruletagame:0', 26)
        set_text('ruletagame:1', '🅿️ RULETAGAME')
        set_text('ruletagame:2', 'Ruleta by AISasha, inspired from Leia (#RIP) and Arya (#RIP). Ruleta è la roulette russa con la pistola, tamburo da tot colpi con tot proiettili al suo interno, si spara e se c\'è il proiettile sei fuori altrimenti rimani.')
        set_text('ruletagame:3', '#registerme|#registrami: Sasha registra l\'utente alla roulette.')
        set_text('ruletagame:4', '#deleteme|#eliminami: Sasha elimina i dati dell\'utente.')
        set_text('ruletagame:5', '#ruletainfo: Sasha manda le informazioni della roulette.')
        set_text('ruletagame:6', '#mystats|#punti: Sasha manda le statistiche dell\'utente.')
        set_text('ruletagame:7', '#ruleta: Sasha cerca di ucciderti.')
        set_text('ruletagame:8', '#godruleta: Sasha ti dà il 50% di probabilità di guadagnare 70 punti, con l\'altro 50% li perdi tutti (richiede almeno 11 punti).')
        set_text('ruletagame:9', '#challenge|#sfida <username>|<reply>: Sasha avvia una sfida tra il mittente e l\'utente specificato, il vincitore vincerà 20 punti mentre il perdente ne perderà 20.')
        set_text('ruletagame:10', '#accept|#accetta: Sasha conferma la sfida.')
        set_text('ruletagame:11', '#reject|#rifiuta: Sasha cancella la sfida, se la sfida è già stata avviata ed è cancellata da uno dei giocatori esso perde 20 punti e viene ucciso.')
        set_text('ruletagame:12', '#challengeinfo: Sasha manda le informazioni della sfida in corso.')
        set_text('ruletagame:13', '#leaderboard|#classifica [(attempts|tentativi)|(deaths|morti)|(streak|serie)|(challenges|sfide)|(victories|vittorie)|(defeats|sconfitte)]: Sasha manda la classifica del parametro specificato, se nulla è specificato manderà quella dei punteggi.')
        set_text('ruletagame:14', 'MOD')
        set_text('ruletagame:15', '#setcaps <value>: Sasha mette <value> proiettili nel tamburo.')
        set_text('ruletagame:16', '#setchallengecaps <value>: Sasha mette <value> proiettili nel tamburo delle sfide.')
        set_text('ruletagame:17', 'OWNER')
        set_text('ruletagame:18', '#setcylinder <value>: Sasha imposta un tamburo da <value> colpi nel range [5-10].')
        set_text('ruletagame:19', '#setchallengecylinder <value>: Sasha imposta un tamburo da <value> colpi per le sfide nel range [5-10].')
        set_text('ruletagame:20', 'ADMIN')
        set_text('ruletagame:21', '(#registergroupruleta|registra gruppo ruleta): Sasha abilita il gruppo a giocare a ruleta.')
        set_text('ruletagame:22', '(#deletegroup|elimina gruppo): Sasha disabilita il gruppo per ruleta.')
        set_text('ruletagame:23', 'SUDO')
        set_text('ruletagame:24', '#createruletadb: Sasha crea il database di ruleta.')
        set_text('ruletagame:25', '#addpoints <id> <value>: Sasha aggiunge <value> punti all\'utente specificato.')
        set_text('ruletagame:26', '#rempoints <id> <value>: Sasha sottrae <value> punti all\'utente specificato.')

        -- set.lua --
        set_text('set:0', 5)
        set_text('set:1', '🅿️ SET')
        set_text('set:2', 'MOD')
        set_text('set:3', '(#set|[sasha] setta) <var_name> <text>: Sasha salva <text> come risposta a <var_name>.')
        set_text('set:4', '(#setmedia|[sasha] setta media) <var_name>: Sasha salva il media (foto o audio) che le verrà inviato come risposta a <var_name>.')
        set_text('set:5', '(#cancel|[sasha] annulla): Sasha annulla un #setmedia.')

        -- shout.lua --
        set_text('shout:0', 2)
        set_text('shout:1', '🅿️ SHOUT')
        set_text('shout:2', '(#shout|[sasha] grida|[sasha] urla) <text>: Sasha "urla" <text>.')

        -- spam.lua --
        set_text('spam:0', 6)
        set_text('spam:1', '🅿️ SPAM')
        set_text('spam:2', 'OWNER')
        set_text('spam:3', '#setspam <text>: Sasha imposta <text> come messaggio da spammare.')
        set_text('spam:4', '#setmsgs <value>: Sasha imposta <value> come numero di messaggi da spammare.')
        set_text('spam:5', '#setwait <seconds>: Sasha imposta <seconds> come intervallo di tempo tra i messaggi.')
        set_text('spam:6', '(#spam|[sasha] spamma): Sasha inizia a spammare.')

        -- stats.lua --
        set_text('stats:0', 13)
        set_text('stats:1', '🅿️ STATS')
        set_text('stats:2', '[#]aisasha: Sasha invia la propria descrizione.')
        set_text('stats:3', 'MOD')
        set_text('stats:4', '(#stats|#messages): Sasha invia le statistiche della chat.')
        set_text('stats:5', '(#realstats|#realmessages): Sasha invia le statistiche con solo i membri del gruppo.')
        set_text('stats:6', '(#cleanstats|#cleanmessages): Sasha pulisce le statistiche.')
        set_text('stats:7', '(#statslist|#messageslist): Sasha invia un file con le statistiche della chat.')
        set_text('stats:8', 'ADMIN')
        set_text('stats:9', '(#stats|#messages) group <group_id>: Sasha invia le statistiche relative al gruppo specificato.')
        set_text('stats:10', '(#realstats|#realmessages) group <group_id>: Sasha invia le statistiche relative al gruppo specificato con solo i membri del gruppo.')
        set_text('stats:11', '(#cleanstats|#cleanmessages) group <group_id>: Sasha pulisce le statistiche relative al gruppo specificato.')
        set_text('stats:12', '(#statslist|#messageslist) group <group_id>: Sasha invia un file con le statistiche relative al gruppo specificato.')
        set_text('stats:13', '(#stats|#messages) aisasha: Sasha invia le proprie statistiche.')

        -- strings_en.lua --
        set_text('strings_en:0', 3)
        set_text('strings_en:1', '🅿️ STRINGS_EN')
        set_text('strings_en:2', 'SUDO')
        set_text('strings_en:3', '(#updateenstrings|#installenstrings|([sasha] installa|[sasha] aggiorna) stringhe en): Sasha updates strings.')

        -- strings_it.lua --
        set_text('strings_it:0', 3)
        set_text('strings_it:1', '🅿️ STRINGS_IT')
        set_text('strings_it:2', 'SUDO')
        set_text('strings_it:3', '(#updateitstrings|#installitstrings|([sasha] installa|[sasha] aggiorna) stringhe it): Sasha aggiorna le stringhe di testo.')

        -- supergroup.lua --
        set_text('supergroup:0', 47)
        set_text('supergroup:1', '🅿️ SUPERGROUP')
        set_text('supergroup:2', '#owner: Sasha manda il proprietario.')
        set_text('supergroup:3', '(#modlist|[sasha] lista mod): Sasha manda la lista dei moderatori.')
        set_text('supergroup:4', '(#rules|sasha regole): Sasha manda le regole del gruppo.')
        set_text('supergroup:5', 'MOD')
        set_text('supergroup:6', '(#bots|[sasha] lista bot): Sasha manda la lista dei bot.')
        set_text('supergroup:7', '#wholist|#memberslist: Sasha manda un file contenente la lista degli utenti.')
        set_text('supergroup:8', '#kickedlist: Sasha manda la lista degli utenti rimossi.')
        set_text('supergroup:9', '#del <reply>: Sasha elimina il messaggio specificato.')
        set_text('supergroup:10', '(#newlink|[sasha] crea link): Sasha crea un nuovo link d\'invito.')
        set_text('supergroup:11', '(#link|sasha link): Sasha manda il link d\'invito.')
        set_text('supergroup:12', '#setname|setgpname <text>: Sasha cambia il nome del gruppo con <text>.')
        set_text('supergroup:13', '#setphoto|setgpphoto: Sasha cambia la foto del gruppo.')
        set_text('supergroup:14', '(#setrules|sasha imposta regole) <text>: Sasha cambia le regole del gruppo con <text>.')
        set_text('supergroup:15', '(#setabout|sasha imposta descrizione) <text>: Sasha cambia la descrizione del gruppo con <text>.')
        set_text('supergroup:16', '(#lock|[sasha] blocca) links|spam|flood|arabic|member|rtl|tgservice|sticker|contacts|strict: Sasha blocca l\'opzione specificata.')
        set_text('supergroup:17', '(#unlock|[sasha] sblocca) links|spam|flood|arabic|member|rtl|tgservice|sticker|contacts|strict: Sasha sblocca l\'opzione specificata.')
        set_text('supergroup:18', '#setflood <value>: Sasha imposta il flood massimo del gruppo a <value>.')
        set_text('supergroup:19', '#public yes|no: Sasha imposta il gruppo come pubblico|privato.')
        set_text('supergroup:20', '#muteuser|voce <id>|<username>|<reply>|from: Sasha imposta|toglie il muto sull\'utente.')
        set_text('supergroup:21', '(#muteslist|lista muti): Sasha manda la lista delle variabili mute della chat.')
        set_text('supergroup:22', '(#mutelist|lista utenti muti): Sasha manda la lista degli utenti muti della chat.')
        set_text('supergroup:23', '#settings: Sasha manda le impostazioni del gruppo.')
        set_text('supergroup:24', 'OWNER')
        set_text('supergroup:25', '(#admins|[sasha] lista admin): Sasha manda la lista degli amministratori.')
        set_text('supergroup:26', '(#setlink|sasha imposta link) <link>: Sasha imposta <link> come link d\'invito.')
        set_text('supergroup:27', '#setadmin <id>|<username>|<reply>: Sasha promuove l\'utente specificato ad amministratore (telegram).')
        set_text('supergroup:28', '#demoteadmin <id>|<username>|<reply>: Sasha degrada l\'utente specificato (telegram).')
        set_text('supergroup:29', '#setowner <id>|<username>|<reply>: Sasha imposta l\'utente specificato come proprietario.')
        set_text('supergroup:30', '(#promote|[sasha] promuovi) <id>|<username>|<reply>: Sasha promuove l\'utente specificato a moderatore.')
        set_text('supergroup:31', '(#demote|[sasha] degrada) <id>|<username>|<reply>: Sasha degrada l\'utente specificato.')
        set_text('supergroup:32', '#clean rules|about|modlist|mutelist: Sasha azzera la variabile specificata.')
        set_text('supergroup:33', '#mute|silenzia all|text|documents|gifs|video|photo|audio: Sasha imposta il muto sulla variabile specificata.')
        set_text('supergroup:34', '#unmute|ripristina all|text|documents|gifs|video|photo|audio: Sasha rimuove il muto sulla variabile specificata.')
        set_text('supergroup:35', 'SUPPORT')
        set_text('supergroup:36', '#add: Sasha aggiunge il supergruppo.')
        set_text('supergroup:37', '#rem: Sasha rimuove il supergruppo.')
        set_text('supergroup:38', 'ADMIN')
        set_text('supergroup:39', '#tosuper: Sasha aggiorna il gruppo a supergruppo.')
        set_text('supergroup:40', '#setusername <text>: Sasha cambia l\'username del gruppo con <text>.')
        set_text('supergroup:41', '#kill supergroup: Sasha elimina ogni utente nel supergruppo e poi lo chiude.')
        set_text('supergroup:42', 'peer_id')
        set_text('supergroup:43', 'msg.to.id')
        set_text('supergroup:44', 'msg.to.peer_id')
        set_text('supergroup:45', 'SUDO')
        set_text('supergroup:46', '#mp <id>: Sasha promuove <id> a moderatore del gruppo (telegram).')
        set_text('supergroup:47', '#md <id>: Sasha degrada <id> dal ruolo di moderatore del gruppo (telegram).')

        -- tagall.lua --
        set_text('tagall:0', 3)
        set_text('tagall:1', '🅿️ TAGALL')
        set_text('tagall:2', 'OWNER')
        set_text('tagall:3', '(#tagall|sasha tagga tutti) <text>: Sasha tagga tutti i membri del gruppo con username e scrive <text>.')

        -- tex.lua --
        set_text('tex:0', 2)
        set_text('tex:1', '🅿️ TEX')
        set_text('tex:2', '(#tex|[sasha] equazione) <equation>: Sasha converte <equation> in immagine.')

        -- unset.lua --
        set_text('unset:0', 3)
        set_text('unset:1', '🅿️ UNSET')
        set_text('unset:2', 'MOD')
        set_text('unset:3', '(#unset|[sasha] unsetta) <var_name>: Sasha elimina <var_name>.')

        -- urbandictionary.lua --
        set_text('urbandictionary:0', 2)
        set_text('urbandictionary:1', '🅿️ URBANDICTIONARY')
        set_text('urbandictionary:2', '(#urbandictionary|#urban|#ud|[sasha] urban|[sasha] ud) <text>: Sasha mostra la definizione di <text> dall\'Urban Dictionary.')

        -- warn.lua --
        set_text('warn:0', 8)
        set_text('warn:1', '🅿️ WARN')
        set_text('warn:2', 'MOD')
        set_text('warn:3', '#setwarn <value>: Sasha imposta gli avvertimenti massimi a <value>, se zero gli avvertimenti non funzioneranno più.')
        set_text('warn:4', '#getwarn: Sasha manda il numero di avvertimenti massimi.')
        set_text('warn:5', '(#getuserwarns|[sasha] ottieni avvertimenti) <id>|<username>|<reply>: Sasha manda il numero di avvertimenti ricevuti dall\'utente.')
        set_text('warn:6', '(#warn|[sasha] avverti) <id>|<username>|<reply>: Sasha avverte l\'utente.')
        set_text('warn:7', '#unwarn <id>|<username>|<reply>: Sasha diminuisce di uno gli avvertimenti dell\'utente.')
        set_text('warn:8', '(#unwarnall|[sasha] azzera avvertimenti) <id>|<username>|<reply>: Sasha azzera gli avvertimenti dell\'utente.')

        -- webshot.lua --
        set_text('webshot:0', 15)
        set_text('webshot:1', '🅿️ WEBSHOT')
        set_text('webshot:2', 'MOD')
        set_text('webshot:3', '(#webshot|[sasha] webshotta) <url> [<size>]: Sasha esegue uno screenshot di <url> e lo invia, se <size> è specificata di quella dimensione.')
        set_text('webshot:4', 'La dimensione può essere:')
        set_text('webshot:5', 'T: (120 x 90px)')
        set_text('webshot:6', 'S: (200 x 150px)')
        set_text('webshot:7', 'E: (320 x 240px)')
        set_text('webshot:8', 'N: (400 x 300px)')
        set_text('webshot:9', 'M: (640 x 480px)')
        set_text('webshot:10', 'L: (800 x 600px)')
        set_text('webshot:11', 'X: (1024 x 768px)')
        set_text('webshot:12', 'Nmob: (480 x 800px)')
        set_text('webshot:13', 'ADMIN')
        set_text('webshot:14', 'F: Pagina intera (può essere un processo molto lungo)')
        set_text('webshot:15', 'Fmob: Pagina intera (può essere un processo lungo)')

        -- whitelist.lua --
        set_text('whitelist:0', 3)
        set_text('whitelist:1', '🅿️ WHITELIST')
        set_text('whitelist:2', 'ADMIN')
        set_text('whitelist:3', '#whitelist <id>|<username>|<reply>: Sasha aggiunge|rimuove l\'utente specificato alla|dalla whitelist.')
        set_text('whitelist:4', '#clean whitelist: Sasha pulisce la whitelist.')

        return lang_text('langUpdate')
    else
        return lang_text('require_sudo')
    end
end

return {
    description = "STRINGS_IT",
    patterns =
    {
        '^[#!/]([Ii][Nn][Ss][Tt][Aa][Ll][Ll][Ii][Tt][Ss][Tt][Rr][Ii][Nn][Gg][Ss])$',
        '^[#!/]([Uu][Pp][Dd][Aa][Tt][Ee][Ii][Tt][Ss][Tt][Rr][Ii][Nn][Gg][Ss])$',
        -- installstrings
        '^([Ss][Aa][Ss][Hh][Aa] [Ii][Nn][Ss][Tt][Aa][Ll][Ll][Aa] [Ss][Tt][Rr][Ii][Nn][Gg][Hh][Ee] [Ii][Tt])$',
        '^([Ii][Nn][Ss][Tt][Aa][Ll][Ll][Aa] [Ss][Tt][Rr][Ii][Nn][Gg][Hh][Ee] [Ii][Tt])$',
        -- updatestrings
        '^([Ss][Aa][Ss][Hh][Aa] [Aa][Gg][Gg][Ii][Oo][Rr][Nn][Aa] [Ss][Tt][Rr][Ii][Nn][Gg][Hh][Ee] [Ii][Tt])$',
        '^([Aa][Gg][Gg][Ii][Oo][Rr][Nn][Aa] [Ss][Tt][Rr][Ii][Nn][Gg][Hh][Ee] [Ii][Tt])$',
    },
    run = run,
    min_rank = 5
    -- usage
    -- SUDO
    -- (#updateitstrings|#installitstrings|([sasha] installa|[sasha] aggiorna) stringhe it)
}